### PR TITLE
functor fixpoint

### PR DESCRIPTION
**Pull request by JosephJNK**
I wrote this for [this project](https://github.com/JosephJNK/static-land-recursion-schemes), but I thought it might make more sense in flow-static-land. Do you think it would be worth adding here?

### CODE REVIEW

**Comment by gcanti** [comment]
Hi @JosephJNK, interesting library! 

Since it contains more than this `Fix` definition, maybe I could just add a link to your library in the README

**Comment by JosephJNK** [comment]
Thanks! A link to the library would be awesome, but I just linked it to show this implementation of `Fix` in action. I meant that since `Fix` lives in `Data.Functor` In Haskell, I think it would make sense for `static-land-recursion-schemes` and any consumers of it to import `Fix` from `flow-static-land`, rather than keeping `Fix` in `static-land-recursion-schemes`. At the same time, I don't know of any uses of `Fix` other than recursion schemes, so I would understand if it was too specialized to belong in `flow-static-land`.

**Comment by gcanti** [comment]
> I don't know of any uses of Fix other than recursion schemes

Neither do I. Just added a link to your lib

**Comment by JosephJNK** [comment]
Great, thanks. I'll close this then.

**Pull request closed without merging**
